---
issues:
  exclude:
    - SA1006  # printf-style function with dynamic format string and no further arguments should use print-style function instead (staticcheck)
    - SA1019  # (deprecated standard library function) (staticcheck)
    - SA6005  # should use strings.EqualFold instead (staticcheck)
