language: go
install:
  - go get -v .
go:
  - 1.0
  - 1.1
  - 1.2
  - tip
after_success:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - export PATH=$PATH:$HOME/gopath/bin/
  - goveralls ywf0TpEcUc19k8FsI6oVSrzdPCkYh2JqI

