language: go
sudo: false
install:
  - go get golang.org/x/crypto/ssh
  - go get -v -tags 'fixtures acceptance' ./...
go:
  - 1.4
  - 1.5
  - tip
env:
  - COVERALLS_TOKEN=2k7PTU3xa474Hymwgdj6XjqenNfGTNkO8
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - script/cibuild
  - $HOME/gopath/bin/goveralls
