name: Pull Request backporting

on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  backporting:
    name: "Backporting"
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
          && contains(github.event.pull_request.labels.*.name, 'backport-v1')
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport-v1')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Backporting
        uses: kiegroup/git-backporting@c19a56a9ad85adf9c74df7b416ec47257f1f8e91
        with:
          target-branch: v1
          pull-request: ${{ github.event.pull_request.url }}
          # We need to use a Personal Access Token (PAT) when creating the pull request because we
          # expect GitHub Actions workflows to be triggered when the pull request is opened.
          # BACKPORT_PR_PAT is a secret that contains that token which will expire on August 1st 2024.
          auth: ${{ secrets.BACKPORT_PR_PAT }}
          no-squash: true
          strategy-option: find-renames
