name: functional-fwaas_v2
on:
  pull_request:
    paths:
      - '**networking/extensions/fwaas_v2**'
  schedule:
    - cron: '0 0 */3 * *'
jobs:
  functional-fwaas_v2:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "master"
            openstack_version: "master"
            ubuntu_version: "22.04"
            devstack_conf_overrides: |
              enable_plugin neutron-fwaas https://opendev.org/openstack/neutron-fwaas master
              enable_plugin neutron-fwaas-dashboard https://opendev.org/openstack/neutron-fwaas-dashboard master
          - name: "zed"
            openstack_version: "stable/zed"
            ubuntu_version: "22.04"
            devstack_conf_overrides: |
              enable_plugin neutron-fwaas https://opendev.org/openstack/neutron-fwaas stable/zed
              enable_plugin neutron-fwaas-dashboard https://opendev.org/openstack/neutron-fwaas-dashboard stable/zed
    runs-on: ubuntu-${{ matrix.ubuntu_version }}
    name: Deploy OpenStack ${{ matrix.name }} with enabled FWaaS_v2 and run networking acceptance tests
    steps:
      - name: Checkout Gophercloud
        uses: actions/checkout@v3
      - name: Deploy devstack
        uses: EmilienM/devstack-action@v0.11
        with:
          branch: ${{ matrix.openstack_version }}
          conf_overrides: |
            Q_AGENT=openvswitch
            Q_ML2_PLUGIN_MECHANISM_DRIVERS=openvswitch,l2population
            Q_ML2_PLUGIN_TYPE_DRIVERS=flat,gre,vlan,vxlan
            Q_ML2_TENANT_NETWORK_TYPE=vxlan
            Q_TUNNEL_TYPES=vxlan,gre
          enabled_services: 'q-svc,q-agt,q-dhcp,q-l3,q-meta,q-fwaas-v2'
          disabled_services: 'ovn,ovn-controller,ovn-northd,q-ovn-metadata-agent,cinder,c-sch,c-api,c-vol,horizon,tempest,swift'
      - name: Checkout go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.15'
      - name: Run Gophercloud acceptance tests
        run: ./script/acceptancetest
        env:
          DEVSTACK_PATH: ${{ github.workspace }}/devstack
          ACCEPTANCE_TESTS_FILTER: "^.*fwaas_v2.*$"
          OS_BRANCH: ${{ matrix.openstack_version }}
      - name: Generate logs on failure
        run: ./script/collectlogs
        if: failure()
      - name: Upload logs artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: functional-fwaas_v2-${{ matrix.name }}
          path: /tmp/devstack-logs/*
